---
title: "flu_merged"
output: github_document
---
Contains script for merging time point data, regressing out cell cycle information, clustering the cells, and finding markers for each cluster

```{r}
# Load in the libraries
library(Seurat)
library(cowplot)
library(tidyverse)
```

```{r naive setup}
# Naive
naive_mat <- Matrix::readMM(file = "~/thesis/flu_GSE202002/flu_data/GSM6086518_Lung_mf_mo_naive_matrix.mtx.gz")
naive_genes <- read.table(file = "~/thesis/flu_GSE202002/flu_data/GSM6086518_Lung_mf_mo_naive_features.tsv.gz")
naive_genes.names <- naive_genes[['V2']]
naive_barcodes <- read.table(file = "~/thesis/flu_GSE202002/flu_data/GSM6086518_Lung_mf_mo_naive_barcodes.tsv.gz")
naive_barcodes.names <- naive_barcodes[['V1']]
colnames(naive_mat) <- naive_barcodes.names
rownames(naive_mat) <- naive_genes.names
naive_SO <- CreateSeuratObject(naive_mat, min.cells = 5)
naive_SO$orig.ident <- "d0"
naive_SO$timepoint <- "d0"
naive_length <- length(naive_SO@active.ident)
```

```{r d7}
# d7
d7_mat <- Matrix::readMM(file = "~/thesis/flu_GSE202002/flu_data/GSM6086519_Lung_mf_mo_flu_d7_matrix.mtx.gz")
# Reading in the genes and formatting the resulting dataframe
d7_genes <- read.table(file = "~/thesis/flu_GSE202002/flu_data/GSM6086519_Lung_mf_mo_flu_d7_features.tsv.gz")
d7_genes.names <- d7_genes[['V2']]
d7_barcodes <- read.table(file = "~/thesis/flu_GSE202002/flu_data/GSM6086519_Lung_mf_mo_flu_d7_barcodes.tsv.gz")
d7_barcodes.names <- d7_barcodes[['V1']]
colnames(d7_mat) <- d7_barcodes.names
rownames(d7_mat) <- d7_genes.names
d7_SO <- CreateSeuratObject(d7_mat, min.cells = 5)
d7_SO$orig.ident <- "d7"
d7_SO$timepoint <- "d7"
d7_length <- length(d7_SO@active.ident)
```

```{r d14}
# d14
d14_mat <- Matrix::readMM(file = "~/thesis/flu_GSE202002/flu_data/GSM6086520_Lung_mf_mo_flu_d14_matrix.mtx.gz")
# Reading in the genes and formatting the resulting dataframe
d14_genes <- read.table(file = "~/thesis/flu_GSE202002/flu_data/GSM6086520_Lung_mf_mo_flu_d14_features.tsv.gz")
d14_genes.names <- d14_genes[['V2']]
d14_barcodes <- read.table(file = "~/thesis/flu_GSE202002/flu_data/GSM6086520_Lung_mf_mo_flu_d14_barcodes.tsv.gz")
d14_barcodes.names <- d14_barcodes[['V1']]
colnames(d14_mat) <- d14_barcodes.names
rownames(d14_mat) <- d14_genes.names
d14_SO <- CreateSeuratObject(d14_mat, min.cells = 5)
d14_SO$orig.ident <- "d14"
d14_SO$timepoint <- "d14"
d14_length <- length(d14_SO@active.ident)
```

```{r day 30}
# d30
d30_mat <- Matrix::readMM(file = "~/thesis/flu_GSE202002/flu_data/GSM6086521_Lung_mf_mo_flu_d30_matrix.mtx.gz")
# Reading in the genes and formatting the resulting dataframe
d30_genes <- read.table(file = "~/thesis/flu_GSE202002/flu_data/GSM6086521_Lung_mf_mo_flu_d30_features.tsv.gz")
d30_genes.names <- d30_genes[['V2']]
d30_barcodes <- read.table(file = "~/thesis/flu_GSE202002/flu_data/GSM6086521_Lung_mf_mo_flu_d30_barcodes.tsv.gz")
d30_barcodes.names <- d30_barcodes[['V1']]
colnames(d30_mat) <- d30_barcodes.names
rownames(d30_mat) <- d30_genes.names
d30_SO <- CreateSeuratObject(d30_mat, min.cells = 5)
d30_SO$orig.ident <- "d30"
d30_SO$timepoint <- "d30"
d30_length <- length(d30_SO@active.ident)
```

```{r}
# Make the "flu list" - a combined list of all the objects to merge
flu.list <- c(naive_SO, d7_SO, d14_SO, d30_SO)
# Iterate through each object in the list to pre-process it
for (i in 1:length(flu.list)) {
    flu.list[[i]] <- subset (flu.list[[i]], nFeature_RNA > 500)
    flu.list[[i]] <- NormalizeData(flu.list[[i]], verbose = TRUE)
    flu.list[[i]] <- FindVariableFeatures(flu.list[[i]], selection.method = "vst", 
        nfeatures = 2000, verbose = TRUE)
}

# Making the anchor dataset
flu.anchors.all <- FindIntegrationAnchors(object.list = flu.list, dims = 1:30)

# Using the anchor dataset to create a final merged object
flu.integrated.all <- IntegrateData(anchorset = flu.anchors.all, dims = 1:30)
```

# After integration --> start here from saved workspace

```{r take flu.integrated.all object loaded in from workspace}
# Reordering the merged object so the timepoints are in chronological order
flu.integrated.all$timepoint<- factor(flu.integrated.all$timepoint, levels = c("d0", "d7", "d14", "d30"))
flu.integrated.all$orig.ident<- factor(flu.integrated.all$orig.ident, levels = c("d0", "d7", "d14", "d30"))
```

```{r}
# Perform the initilization steps on the integrated Seurat object
DefaultAssay(flu.integrated.all) <- "integrated" # set DefaultAssay to "integrated"
flu.integrated.all <- FindVariableFeatures(flu.integrated.all, selection.method = "vst")
flu.integrated.all <- ScaleData(flu.integrated.all, features = rownames(flu.integrated.all))
```

```{r regress out cell cycle info}
# Cell cycle score the data
flu.integrated.all <- CellCycleScoring(flu.integrated.all, s.features = sgenes, g2m.features = g2mgenes, set.ident = TRUE)

# view cell cycle scores and phase assignments
head(flu.integrated.all[[]])

# Visualize the distribution of cell cycle markers across
RidgePlot(flu.integrated.all, features = c("Pcna", "Top2a", "Mcm6", "Mki67"), ncol = 2)

# Regress out cell cycle information
flu.integrated.all <- ScaleData(flu.integrated.all, vars.to.regress = c("S.Score", "G2M.Score"), features = rownames(flu.integrated.all))
```

```{r}
# Complete the rest of the processing steps now that we've regressed out cell cycle info
flu.integrated.all <- RunPCA(flu.integrated.all, features = VariableFeatures(flu.integrated.all), nfeatures.print = 10)
flu.integrated.all <- RunUMAP(flu.integrated.all, reduction = "pca", dims = 1:30)
flu.integrated.all <- FindNeighbors(flu.integrated.all, reduction = "pca", dims = 1:30)
flu.integrated.all <- FindClusters(flu.integrated.all, resolution = 0.5)
```

```{r}
# Visualization
p1 <- DimPlot(flu.integrated.all, reduction = "umap", group.by = "timepoint")
p2 <- DimPlot(flu.integrated.all, reduction = "umap", label = TRUE)
plot_grid(p1, p2)
DimPlot(flu.integrated.all, split.by = "timepoint")
```

```{r}
# Find markers for the clusters in the flu.integrated.all object
flu.all.markers <- FindAllMarkers(flu.integrated.all, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
```