---
title: "flu_plotting"
output: github_document
date: '2023-02-17'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load libraries for plotting}
library(Seurat)
library(tidyverse)
library(cowplot)
# load workspace with objects
load("~/thesis/flu data and prelim analysis/flu_integrated_ws.RData")
```

```{r alveolar macrophages}
Idents (flu.integrated.all) <- "old.ident"
FeaturePlot(flu.integrated.all, features = c("Pparg", "Siglecf"), cols = c("grey", "red"), order = T, label = TRUE)
VlnPlot(flu.integrated.all, features = c("Siglecf", "Pparg"), group.by = "old.ident", pt.size = 0)
```

```{r interstitial macrophages}
Idents (flu.integrated.all) <- "old.ident"
FeaturePlot(flu.integrated.all, features = c("C1qa", "C1qb", "C1qc"), cols = c("grey", "red"), order = T, label = TRUE)
VlnPlot(flu.integrated.all, features = c("C1qa", "C1qb", "C1qc"), group.by = "old.ident", pt.size = 0)
```



# Plot out MHC I, II expression
```{r MHC I genes}
VlnPlot(flu.integrated.all, features = "MHCI_genes1", group.by = "celltype", split.by = "timepoint", pt.size = 0)
```

```{r}
DoHeatmap(flu.plotting.copy, features = c("Ccr5", "H2-Aa", "H2-Eb1")) + NoLegend()
RidgePlot(object = flu.plotting.copy, features = c("Ccr5", "H2-Aa", "H2-Eb1"))
VlnPlot(flu.plotting.copy, features = c("Ccr5", "H2-Aa", "H2-Eb1"), pt.size = 0)
```

```{r}
FeaturePlot(flu.integrated.all, features = c("Siglecf", "Pparg", "Epcam"), max.cutoff = 3, cols = c("grey", "red"), order = T, split.by = "timepoint", label = TRUE)
VlnPlot(flu.integrated.all, features = c("Siglecf", "Pparg", "Epcam"), pt.size = 0, split.by = "timepoint", group.by = "celltype")
```

```{r}
MHCI_vln_plot <- VlnPlot(flu.plotting.copy, features = c("MHCI_genes1"), group.by = "timepoint", pt.size = 0) + ggtitle("MHC I")
MHCII_vln_plot <- VlnPlot(flu.plotting.copy, features = c("MHCII_genes1"), group.by = "timepoint", pt.size = 0) + ggtitle("MHC II")
plot_grid(MHCI_vln_plot, MHCII_vln_plot, nrow = 2)
```

