---
title: "flu_plotting"
output: github_document
date: '2023-02-17'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load libraries for plotting}
library(Seurat)
library(tidyverse)
library(cowplot)
# load workspace with objects
load("~/thesis/flu data and prelim analysis/flu_integrated_ws.RData")
```

# List of upregulated genes
```{r}
# See what genes are up at d14 compared to d0 in proliferating AMs and AMs
Idents(flu.no.IMs) <- "celltype.time"
bulk_AM_14_v_0 <- FindMarkers(flu.no.IMs, ident.1 = c("bulk_AMs_d14"), ident.2 = c("bulk_AMs_d0"), only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
bulk_AM_14_v_30 <- FindMarkers(flu.no.IMs, ident.1 = c("bulk_AMs_d14"), ident.2 = c("bulk_AMs_d30"), only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
AM_30_v_0 <- FindMarkers(flu.trimmed, ident.1 = c("AMs_d30"), ident.2 = c("AMs_d0"), only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
```

# Figure 3
```{r}
#A
Idents(flu.integrated.all) <- "seurat_clusters"
DimPlot(flu.integrated.all, reduction = "umap", label = TRUE)

#B
DimPlot(flu.integrated.all, reduction = "umap", group.by = "timepoint") + ggitle("")
```

# Figure 4
```{r}
#A
VlnPlot(flu.integrated.all, features = c("Mki67", "Pclaf", "Top2a"), pt.size = 0)

#B
VlnPlot(flu.integrated.all, features = c("Ace", "Adgre4"), pt.size = 0)

#C
VlnPlot(flu.integrated.all, features = c("Klf2", "Ifitm6"), pt.size = 0)

#D
VlnPlot(flu.integrated.all, features = c("H2-Eb1", "H2-Ab1"), pt.size = 0)

#E
VlnPlot(flu.integrated.all, features = c("Ear1", "Ear2"), pt.size = 0)
```

# Figure 5
```{r}
Idents(flu.integrated.all) <- "celltype"
DimPlot(flu.integrated.all, reduction = "umap", label = TRUE)
```

# Figure 6
```{r}
#A
RidgePlot(flu.no.IMs, features = c("Mmp14"))

#B
RidgePlot(flu.no.IMs, features = c("Fn1"))
```

# Figure 7
```{r}
#A
RidgePlot(flu.no.IMs, features = c("MHCI_genes1")) + ggtitle("MHC I")

#B
RidgePlot(flu.no.IMs, features = c("MHCII_genes1")) + ggtitle("MHC II")

#C
RidgePlot(flu.no.IMs, features = c("MHCII_genes1")) + ggtitle("MHC II")
```


# Figure 8
```{r}
#A
RidgePlot(flu.no.IMs, features = c("Ccr5"))

#B
RidgePlot(flu.no.IMs, features = c("Cxcl9"))

#C
RidgePlot(flu.no.IMs, features = c("Cxcl16"))
```

# Figures 9 and 10 were generated in Prism.